{$title = 'Pages'}
{block #js}
	{include #parent}
    {*<script type="text/javascript" src="{$basePath}/js/widgets/jHtmlArea-0.7.0.js"></script>*}
	{widget js 'datagrid.js', 'shadowbox/shadowbox.js','jHtmlArea-0.7.0.min.js', 'widgets/jqueryFileTree.js','jquery.elastic.js', 'pages.js'}
{/block}
{block #css}
	{include #parent}
	{widget css 'pages.css', 'widgets/jHtmlArea.css', 'elastic.css', 'shadowbox.css', 'preview.css', 'widgets/confirmationdialog.css', 'widgets/datagrid.css', 'jHtmlArea.css', 'widgets/jqueryFileTree.css'}
{/block}
@{block #content}
    <div id="link">
        {$link}
    </div>
	{snippet grid}
        @{widget pagesGrid}
    {/snippet}
    {widget confirmForm}
@{/block}
@{block #forms}
	{snippet form}
		{if $new == true}
            <script type="text/javascript">
                  //$('#frmformNewPage-content').htmlarea();
            </script>
			<div id="pageEditor" class="ui-corner-all">
				<h2>{_'New page'}</h2>
				{widget formNewPage}

			</div>
		{/if}
		{if $edit == true}
            <script type="text/javascript">
              //$('#frmformEditPage-content').htmlarea();
            </script>
			<div id="pageEditor" class="ui-corner-all">
				<h2>{_'Edit page'} {if isset($page)}{$page}{/if}</h2>
				{widget formEditPage}
			</div>
		{/if}
               <div id="file_browser" class="ui-corner-all"><h3></h3><div class="browser"/></div>
	{/snippet}
@{/block}